### ISSUE TITLE
Review some errors due to type hints

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#132]
https://twitter.com/andre_roberge/status/1357634078460309505/photo/1

**Comment by alexmojaki** [comment]
`isinstance(x, types.GenericAlias)` seems like a good way to guess when this is the problem.

**Comment by aroberge** [comment]
I had started to think of this case, but never thought of this simpler approach which should work.

**Comment by aroberge** [comment]
This should be added to the linter, if it ever gets written.
