### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#144]
Background: I'm currently working at [GristLabs](https://www.getgrist.com/), the creators of `asttokens`. It's a bit like a spreadsheet, and formulas are written in Python. I'm in the process of integrating friendly-traceback so that formula errors show a friendly explanation, similar to futurecoder. Separately, we're also looking at ways of making writing formulas easier for users in general. This is one point that came up in the discussion.

Both of these expressions are correct Python:

```python
sum(x for x in y if f(x))
len([x for x in y if f(x)])
```

So it's confusing to beginners when this doesn't work:

```python
len(x for x in y if f(x))
```

This could maybe be handled in Grist directly, but since we're soon going to be using friendly-traceback I thought it was best to handle it here where other projects could also benefit.

**Comment by aroberge** [comment]
Thanks for suggesting this as an addition to friendly_traceback instead of handling it separately.  I can definitely look at it; or you can of course submit the code yourself! ;-)

If you use some objects specific to modules created by GristLabs that can raise custom exceptions that would be of no use for others, you can extend friendly_traceback by registering custom handlers.  An example is given in https://friendly-traceback.github.io/docs/custom_errors.html. I have started creating a "fake project [1]" illustrating how to do this in more details. I've written some code for this but have not yet updated the repository. I'm working on this as someone has contacted me as they thought of doing such an extension for pandas. This particular project is ready to start [2].

[1] https://github.com/friendly-traceback/friendly-custom-exception
[2] https://github.com/friendly-traceback/friendly-pandas

**Comment by aroberge** [comment]
Proposed solution:
```
> python -m friendly_traceback

Friendly-traceback version 0.5.46. [Python version: 3.10.6]
Type 'Friendly' for help on special functions/methods.

[1]: nb = len(letter for letter in "word")

Traceback (most recent call last):
  Code block [1], line 1
    nb = len(letter for letter in "word")
TypeError: object of type 'generator' has no len()

        You likely need to build a list first.


[2]: why()

    I am guessing that you were trying to count the number of elements
    produced by a generator expression. You first need to capture them
    in a list:

        len([letter for letter in "word"])


[3]: where()

    Exception raised on line 1 of code block [1].

    -->1: nb = len(letter for letter in "word")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

            len:  <builtin function len>
```
Note: the version number has not been updated.

If this seems acceptable, I will do a commit first so that you can examine what I have done, after which I can upload a new version to Pypi.

**Comment by alexmojaki** [comment]
Looks great!

**Comment by aroberge** [comment]
Note that, unfortunately, this fails if such a statement is written on two lines:
```
> python -m friendly_traceback ignore.py
friendly_traceback\info_variables.py:120 get_all_objects
    f"Problem with ASTTokens: {e}" + f"\nline: {line}": (
        'Problem with ASTTokens: invalid syntax (<unknown>, line 1)\n'
        'line: len(letterforletterin"word")'
    ) (str) len=93
friendly_traceback\info_variables.py:120 get_all_objects
    f"Problem with ASTTokens: {e}" + f"\nline: {line}": (
        'Problem with ASTTokens: invalid syntax (<unknown>, line 1)\n'
        'line: len(letterforletterin"word")'
    ) (str) len=93

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 1, in <module>
    nb = len(letter
TypeError: object of type 'generator' has no len()

        You likely need to build a list first.

    A `TypeError` is usually caused by trying
    to combine two incompatible types of objects,
    by calling a function with the wrong type of object,
    or by trying to do an operation not allowed on a given type of object.

    I am guessing that you were trying to count the number of elements
    produced by a generator expression. You first need to capture them
    in a list:

        len([letterforletterin"word"])

    Exception raised on line 1 of file HOME:\github\friendly-traceback\ignore.py.

    -->1: nb = len(letter
               ^^^^^^^^^^
       2:          for letter in "word")
                   ^^^^^^^^^^^^^^^^^^^^^

            len:  <builtin function len>
```

**Comment by alexmojaki** [comment]
My first reaction was that this might be related to https://github.com/gristlabs/asttokens/pull/50. But why are the spaces missing? Is this a tokenize/untokenize problem?

**Comment by aroberge** [comment]
It appears to be a problem with the node obtained from stack_data/executing
```
self.tb_data.node_text='len(letterforletterin"word")'
```

**Comment by aroberge** [comment]
```
self.node=<ast.Call object at 0x00000158367215E0>
self.node_text='len(letterforletterin"word")'
```

**Comment by alexmojaki** [comment]
I don't think stack_data/executing/asttokens has a problem here:

```python
import stack_data

try:
  len(letter
      for letter in "word")
except Exception as e:
  print(repr(stack_data.FrameInfo(e.__traceback__).executing.text()))
  # 'len(letter\n      for letter in "word")'
```

I think the problem must be here:

https://github.com/friendly-traceback/friendly-traceback/blob/ceef5364ae8e42e108ee3427c309e7f952704c62/friendly_traceback/frame_info.py#L244-L247

**Comment by aroberge** [comment]
Yes, you are correct.  I will fix this by using `token_utils.untokenize` instead, and replacing multiple spaces by a single space.

**Comment by aroberge** [comment]
Fixed:
```
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 1, in <module>
    nb = len(letter
TypeError: object of type 'generator' has no len()

        You likely need to build a list first.

    A `TypeError` is usually caused by trying
    to combine two incompatible types of objects,
    by calling a function with the wrong type of object,
    or by trying to do an operation not allowed on a given type of object.

    I am guessing that you were trying to count the number of elements
    produced by a generator expression. You first need to capture them
    in a list:

        len([letter for letter in "word"])

    Exception raised on line 1 of file HOME:\github\friendly-traceback\ignore.py.

    -->1: nb = len(letter
               ^^^^^^^^^^
       2:          for letter in "word")
                   ^^^^^^^^^^^^^^^^^^^^^

            len:  <builtin function len>
```

Here's the new code that I use instead of joining the tokens:
```
            tokens = [tok for tok in tokens if tok != "\n"]
            node_text = token_utils.untokenize(tokens)
            # Replace multiple spaces by single space
            node_text = " ".join(node_text.split())
```

I'll come back to this in a couple of hours.

**Comment by aroberge** [comment]
New version uploaded to Pypi.

**Comment by aroberge** [comment]
The multiline test case fails for Python 3.11; however this is not unexpected.

The highlighted region for the multiline test case is done wrong for Python 3.6 and 3.7, but the analysis is still done correctly.

**Comment by aroberge** [comment]
Node to self: do not close this issue. Implement a fix in case executing cannot find a node, as discussed in the recent commit.

**Comment by alexmojaki** [comment]
> The highlighted region for the multiline test case is done wrong for Python 3.6 and 3.7, but the analysis is still done correctly.

What do you mean by this? Why is there no sign of it in the test?

**Comment by aroberge** [comment]
```
...
    I am guessing that you were trying to count the number of elements
    produced by a generator expression. You first need to capture them
    in a list:

        len([letter for letter in "word"])

    Exception raised on line 2 of file HOME:\github\friendly-traceback\ignore.py.

       1: nb = len(letter
    -->2:          for letter in "word")
               ^^^^^^^^^^^^^^^^^^^^^^^^^

            len:  <builtin function len>
```

**Comment by aroberge** [comment]
Yes, I will need to investigate this. Mind you, 3.6 is no longer supported and before long 3.7 will be dropped as well. I wonder how long I should keep supporting 3.6.

**Comment by alexmojaki** [comment]
I doubt this is really a version issue. It seems more like a case of your 'underlining' algorithm being sensitive to the exact `frame.f_lineno`.

**Comment by aroberge** [comment]
I completely agree that the problem is likely in the way that my own 'underlining' algorithm works. 

Anyway, I just pushed a new commit for more robust handling of the `bad_line`. I will need to look at the issue of underlining later as work is calling.

**Comment by aroberge** [comment]
@alexmojaki I was able to make some small changes to `stack_data` so that it does a better job formatting the test case. Using Python 3.9, where the highlight line is 5
```
> python example.py
Traceback (most recent call last):
 File "C:\Users\Andre\github\stack_data\example.py", line 5, in <module>
       1 | import stack_data
       3 | stack_data.Formatter().set_hook()
-->    5 | nb = len(letter
                ^^^^^^^^^^
       6 |          for letter in "word")
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'generator' has no len()
```
Using Python 3.6, where the highlighted line is 6:
```
(venv3.6) C:\Users\Andre\github\stack_data
> python example.py
Traceback (most recent call last):
 File "C:\Users\Andre\github\stack_data\example.py", line 6, in <module>
       1 | import stack_data
       3 | stack_data.Formatter().set_hook()
       5 | nb = len(letter
                ^^^^^^^^^^
-->    6 |          for letter in "word")
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'generator' has no len()
```
I tried to run pytest on my fork but got an error about missing pyximport (which, I gather, is related to Cython).

My fix only requires some small changes which you could presumably change by hand in your repo and see if all the tests still pass - perhaps adding the one shown here as an additional test.
You can see the changes at https://github.com/aroberge/stack_data/commit/35b798bf100fd2427f937c9d351c8c0b3893b063

**Comment by rootsmusic** [comment]
@alexmojaki (Just browsing issues.) I think @aroberge fixed this issue with his commit above.

**Comment by alexmojaki** [comment]
I think you're right :)
