### ISSUE TITLE
Review manipulations of `bad_line` in runtime errors

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#147]
In a discussion https://github.com/friendly-traceback/friendly-traceback/commit/783129ce53f2a9b235a2efac092614bd4b4451b6, @alexmojaki pointed out that what I was doing with `bad_line` assumed that `executing` was extracting the node information correctly. I since made the required corrections for that particular case.

I mostly use the content of `bad_line` when dealing with SyntaxErrors. In this case, I don't rely on `executing` to extract the correct information. In addition, I almost always verify the proposed changes to ensure that they do not contain SyntaxErrors.

I need to review in the runtime error cases where I use the information from `bad_line` and either confirm that it is appropriate or add safeguards. The modules to review are:

- [ ] attribute_error.py
- [ ] file_not_found_error.py
- [ ] import_error.py
- [ ] index_error.py
- [ ] key_error.py
- [ ] module_not_found_error.py
- [ ] name_error.py
- [ ] os_error.py
- [ ] runtime_error.py
- [ ] type_error.py
- [x] unbound_local_error.py
- [ ] value_error.py
- [ ] zero_division_error.py

**Comment by alexmojaki** [comment]
To be clear, I don't think you need to worry too much that executing might identify the wrong node. I don't know of any case where that's happened and I've been careful to ensure that it doesn't. But it might not identify a node at all. I should probably make this point clearer at the start of https://github.com/alexmojaki/executing#is-it-reliable

**Comment by aroberge** [comment]
If it does not identify a node, then `bad_line` still gets a value, something like
```
bad_line = self.records[-1].problem_line()
```
If `node_text` is defined, then we know that it is more precise than the line flagged in the traceback and `bad_line` gets replaced by `node_text`.
