### ISSUE TITLE
Make better use of stack_data

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#152]
With version 0.5.0, `stack_data` now has an option for not skipping blank lines, which I consider to be preferable for beginners. It would be more efficient to remove my custom code and replace it by `stack_data`'s version. While doing so, I should also change the way I locate where the exception was raised and the last call in the user's code as it is not very efficient and contains some duplication with the `detailed_tb` newest addition.

Currently, `friendly_traceback` separates the line number from the code using a colon; `stack_data` does it using a vertical bar, `|`, which does look better. However, `friendly` assumes that a colon is used. So, before changing `friendly_traceback`, I need to upload a new version, and upload a new version of `friendly` that uses this specific version of `friendly_traceback` while work is being done. The same should likely be done for `friendly_idle`.

There are other changes that should be taken care of while working on this issue, and they are as follows:

- [x] Upload a new version of `friendly_traceback`   (0.5.48)
- [x] Upload a new version of `friendly`  (0.5.36)
- [x] Create a new version of the documentation. This will help spot possible regressions.
- [x] Replace the combined computation to obtain "partial source" and "problem line" into two different operations.
   - [x] Ensure that all tests in the documentation remain unchanged
- [x] Extract info about first/last call in traceback from `detailed_tb`.
   - [x] Confirm again that all tests in the documentation remain unchanged.
- [x] Use `stack_data` to obtain `detailed_tb`.
   - [x] Update the documentation and examine carefully to confirm that the only significant changes are replacement of `:` by `|` (with some possibility of other minor differences in spacing)
- [x] Upload new version to Pypi
- [x] Work separately to make `friendly` and `friendly_idle` compatible with this new version.

**Comment by aroberge** [comment]
@alexmojaki I'm trying to use `stack_data` to format the traceback content of a single frame, but it does not work.

As a specific example, given the following test file:
```
a = 'hello'

print(a[5])
```
friendly_traceback currently show the following:
```
       1: a = 'hello'
       2:
    -->3: print(a[5])
                ^^^^
```
For now, all I want is show essentially the information including the blank line (2).

So, I tried to use `stack_data` with the `BlankLines.SINGLE` option to replace https://github.com/friendly-traceback/friendly-traceback/blob/99bb2bfc86f25daa1e84812ab208282afc42747a/friendly_traceback/frame_info.py#L89.  

As a first step, I thought to define a formatter inside this function, have it yields some lines that I can print and compare with the current output from friendly_traceback. I can get it to do this, but it ignores the `BlankLines.SINGLE` option, and uses the default `BlankLines.HIDDEN` instead.

That is, after adding the required import statements, if I insert the following:
```
        for line in Formatter(options=Options(blank_lines=BlankLines.SINGLE)).format_frame(self):
            print(line, end="")
```

the result is
```
 File "C:\Users\Andre\github\friendly-traceback\ignore3.py", line 3, in <module>
       1 | a = 'hello'
-->    3 | print(a[5])
                 ^^^^
```
So, line 2 is skipped, which is not what I want.  As an aside, eventually, I will not want to include the header in the output from this method.

After looking closely, I figured that this was because the FrameInfo object was already set with some defined options. 
I first tried to add the options to the frame object,
```
        self.options = Options(blank_lines=BlankLines.SINGLE)
        for line in Formatter().format_frame(self):
            print(line, end="")
```
but it did not change anything.

So, I tried to add this option to https://github.com/friendly-traceback/friendly-traceback/blob/99bb2bfc86f25daa1e84812ab208282afc42747a/friendly_traceback/core.py#L134 but it raises the following exception 
```
 AttributeError("'BlankLineRange' object has no attribute 'is_current'")
```

To be more specific, here's what I wrote and which raises the exception:
```
            all_records = list(FrameInfo.stack_data(tb,
                                                    Options(blank_lines=BlankLines.SINGLE),
                                                    collapse_repeated_frames=False))
```


Clearly, I don't understand how `stack_data` works well enough. I was wondering if you could have a look at it and hopefully see quickly what needs to be done and give me some pointers.

**Comment by aroberge** [comment]
@alexmojaki Please ignore the previous request for help. I had suppressed some exceptions which prevented me from finding out the cause of the `AttributeError` being raised.

**Comment by alexmojaki** [comment]
> As an aside, eventually, I will not want to include the header in the output from this method.

Should be easy:

```python
    def format_frame_header(self, frame_info: FrameInfo) -> str:
        return ''
```

> After looking closely, I figured that this was because the FrameInfo object was already set with some defined options.

I think this is a good point about the usability of the API which could be improved. Formatters generally assume that callers will use a higher level API such as `format_exception`, and so they will pass its own options to the core. But what you did is not unreasonable and it's a mistake we'd want to prevent. We could change this:

```python
    def format_frame(self, frame: Union[FrameInfo, FrameType, TracebackType]) -> Iterable[str]:
        if not isinstance(frame, FrameInfo):
            frame = FrameInfo(frame, self.options)
```

to this:

```python
    def format_frame(self, frame: Union[FrameInfo, FrameType, TracebackType]) -> Iterable[str]:
        if isinstance(frame, FrameInfo):
            assert_(self.options in (frame.options, None))
        else:
            frame = FrameInfo(frame, self.options)
```

> I first tried to add the options to the frame object, ... but it did not change anything.

This surprised me. Was there an interesting reason why it didn't work?

**Comment by aroberge** [comment]
The reason was my own stupidity. In some other parts of my code, I worked with `Line` objects and never checked to see if they could be `BlankLines` objects - the newest addition.

Now, everything works and I'm just cleaning things up.

I did have to prevent an `AssertionError` when trying to use `stack_data` to highlight the following:
```
code = compile("1/0", "<fake>", "exec")
exec(code)
```
I also needed to write my own formatter as I didn't like some additional hard-formatting spaces used by default in `stack_data`.

**Comment by aroberge** [comment]
Sorry, I realised that I misread your question ...

When I tried to add the options to the frame object, I did so in a later method and I suspect that by that time, the line objects were already all created, with no `BlankLine` object added.

**Comment by alexmojaki** [comment]
Ah, that makes sense. I suppose the general lesson is that setting attributes yourself rather than via the recommended API and constructors is dangerous. We could maybe make the more explicit in stack_data, but maybe it's not worth it.

**Comment by aroberge** [comment]
I agree that it is not worth it to change anything with `stack_data`.  The problem in my case is that I was already using an older version and I didn't systematically go through all the places I was using it to ensure that they were all consistent with the newest version.
