### ISSUE TITLE
"Friendly-traceback does not know the cause of this error."

### ISSUE THREAD

**Issue by Thrylos53** [friendly-traceback/friendly-traceback#155]
In HackInScience, on the Next Prime level, I was told to report my code here.

Here is my code:

import itertools
import math
import sys

def prime(base):
    is_prime(itertools.count(base))
    
def is_prime(n):
    if n <= 1:
        return False
    else:
        for i in range(2,math.isqrt(n)+1):
            if n % i == 0:
                return False 
        return True
        
        
prime(100000000)

**Comment by aroberge** [comment]
Thanks for reporting this.

Recording the actual message below, using an interactive session.
```
[1]: import itertools

[2]: import math

[3]: def prime(base):
...:     is_prime(itertools.count(base))
...:

[4]: def is_prime(n):
...:     if n <= 1:
...:         return False
...:     else:
...:         for i in range(2, math.isqrt(n)+1):
...:             if n%i ==0:
...:                 return False
...:     return True
...:

[5]: prime(100000000)

Traceback (most recent call last):
  Code block [5], line 1
    prime(100000000)
  Code block [3], line 2
    is_prime(itertools.count(base))
  Code block [4], line 2
    if n <= 1:
TypeError: '<=' not supported between instances of 'itertools.count' and 'int'

Friendly-traceback does not know the cause of this error.
```
