### ISSUE TITLE
Default Language for friendly

### ISSUE THREAD

**Issue by TamilNeram** [friendly-traceback/friendly-traceback#159]
1) Need to have a automated way of picking up OS language settings during import of friendly module.
2) Use that OS language as default if the optional argument is not supplied. i.e. --lang option.

**Comment by aroberge** [comment]
Issue moved to https://github.com/friendly-traceback/friendly/issues/40 since users should use `friendly` instead of `friendly-traceback`.

**Comment by aroberge** [comment]
@TamilNeram This has been implemented (but not tested in a non-English environment) for **friendly**. 

If only friendly_traceback is used, the language needs to be specified explicitly.

The last language used is saved by friendly, and is the one used when resuming the next session.

**Comment by TamilNeram** [comment]
Thanks :)
