### ISSUE TITLE
Make it easier to add message parsers when extending friendly_traceback

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#165]
Currently, with the new friendly-pandas project, I reuse an existing message parser for `KeyError`, by importing it. It would be much better to do something like this:
```
from runtime_message_parser import MessageParser
parser = get_parser(KeyError)
```
and have it return an existing message parser (in this case) or a new one (if friendly_traceback had not already created one for `KeyError`).

As part of this change, replace parser.add by parser._add, signaling that this method is internal to Friendly, and have parser.add for external projects.

Also, the message parsers should be passed two object, the message and `tb_data` instead of three.

- [x] new `RuntimeMessageParser` class in separate file
- [x] remove frame from the call
- [x] rename the first argument `message`
- [x] change `parser.add` to `message_parser._add` for greater clarity
- [x] rename `RuntimeMessageParser.add_custom` to `RuntimeMessageParser.add`

**Comment by aroberge** [comment]
As part of this change, replace `parser.add` by `parser._add`, signaling that this method is internal to Friendly, and have `parser.add` for external projects.

**Comment by aroberge** [comment]
@hoefling Hi! Please note that work done in this branch will break custom registration as `info_specific` is being removed. You might want to pin friendly_traceback version to <= 0.5.59.

The new approach will be described in https://github.com/friendly-traceback/friendly-custom-exception

**Comment by hoefling** [comment]
@aroberge I like the changes, IIUC it means less boilerplate when registering a custom error reporter as right now it boils down to:
```python
from friendly_traceback.core import TracebackData
from friendly_traceback.message_parser import get_parser
from friendly_traceback.typing_info import CauseInfo


class MyError(Exception):
    pass


@get_parser(MyError).add
def report(value: MyError, tb_data: TracebackData) -> CauseInfo:
    return {'cause': 'spam', 'suggest': 'eggs'}
```
If I understand it correctly, the only nitpick from my side would be that `RuntimeMessageParser._add` and `RuntimeMessageParser.add` both return `None`. This makes the decorated function to `None`, and I often invoke them directly in unit tests to skip the whole exception raising machinery. I will open a PR shortly that proposes returning the function from both decorators.
