### ISSUE TITLE
executing and linecache

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#174]
https://github.com/alexmojaki/executing/pull/46 is the difference between executing versions 0.9.1 and 1.0.0. It changed how `executing` interacts with `linecache` to better handle source files changing their contents. `Source` objects are no longer cached by filename at all, but only by the lines returned by `linecache`. See https://github.com/alexmojaki/executing/blob/master/executing/executing.py#L277-L284.

friendly-traceback patches `linecache.getlines` and does this:

https://github.com/friendly-traceback/friendly-traceback/blob/fa970a3cdb30b18598b6230dfd6613ed3e4a3f5a/friendly_traceback/source_cache.py#L71-L72

That means each call to `getlines` returns a different list of lines each time as the list keeps getting modified, and the Source cache becomes useless. Changing to `return lines + ["\n"]` instead should fix things.

**Comment by aroberge** [comment]
It most definitely worked and made the tests really fast, especially for 3.11, but I don't understand how adding a list is different to appending an element in this case.

Comparison:
* without this change, executing 1.1.0, tests were completed in 19s
* without this change, older version of executing, tests were completed in 8 s.
* WITH this change, executing 1.1.0 and Python <= 3.10, tests were completed in 5 s.
* WITH this change, executing 1.1.0 and Python 3.11, tests are completed in 3 s. !!

I would never have come up with this fix myself. Thank you very much.

**Comment by alexmojaki** [comment]
> I don't understand how adding a list is different to appending an element in this case.

Because the same list object is kept in your source cache, and each `getlines` adds a new item to the end. Calling `getlines` 1000 times adds 1000 newlines to the list. `tuple(lines)` is used as the cache key in `executing` and that cache key is different every time.

> WITH this change, executing 1.1.0 and Python <= 3.10, tests were completed in 5 s.

I wasn't expecting this improvement but I can see how that could have happened as a result of the changes in moving to executing 1.0.0.

> WITH this change, executing 1.1.0 and Python 3.11, tests are completed in 3 s. !!

Very much expected, the new method in 3.11 is significantly faster as matching code positions is much simpler than the old method.

https://github.com/gristlabs/asttokens/pull/93 will enable further performance improvements in Python 3.8+ that will probably be quite dramatic.
