### ISSUE TITLE
Add support for exception notes

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#181]
Exception notes have been added in Python 3.11. I should add a way to display them.

**Comment by alexmojaki** [comment]
Ooooh, I didn't know about that, great that they added such a feature. stack_data should know about them too.

**Comment by aroberge** [comment]
Support for exception notes has been added to both friendly_traceback and friendly. (I have not checked for Jupyter support for the latter.)

Exemple from Python 3.11:
![image](https://user-images.githubusercontent.com/629698/194727779-3f791af0-485f-4978-92aa-527f759df761.png)

Basic "friendly formatting"
![image](https://user-images.githubusercontent.com/629698/194727791-25ced45f-3a7a-4f64-9545-89dddf721802.png)

The "normal" Python traceback shown by friendly_traceback unfortunately does not exactly match the output from Python as it includes an extra blank line.

![image](https://user-images.githubusercontent.com/629698/194727845-987c3bf2-afe8-4bc4-8a31-87e14881badc.png)

Now, demonstrating with friendly:
![image](https://user-images.githubusercontent.com/629698/194727873-9f770f70-309b-4d23-a3c6-8cbc387476db.png)

For the Python traceback shown by friendly, I just omit the header, but keep the formatting of the notes.

![image](https://user-images.githubusercontent.com/629698/194727898-751cf680-cdc9-4012-977a-8d675b5e65f8.png)

Finally, an example using IDLE:
![image](https://user-images.githubusercontent.com/629698/194727925-97e69f3d-1064-4290-aa24-185ac6c6f876.png)

**Comment by aroberge** [comment]
I need to provide an explanation if a user tries to add a note to an exception for Python versions 3.10 and older.
