### ISSUE TITLE
Код не выполняется

### ISSUE THREAD

**Issue by Dmitry-Baz** [friendly-traceback/friendly-traceback#233]
Доброго дня. Учусь в Синергии. Этот код из учебного примера. И у преподавателя он работает, а у меня нет. 

class Map:
 
    def print_map(self):
        for row in self.cells:
            for cell in row:
                if cell == 0:
                    print('🟩', end="")
                elif cell == 1:
                    print('🌲', end="")
                elif cell == 2:
                    print('🌊', end="")
            print()

def __init__(self, w, h):
    self.cells = [[0 for i in range(w)] for j in range(h)]

tmp = Map(10, 10)
tmp.print_map()

**Comment by aroberge** [comment]
(Переведено Google)
Возможно, вы допустили ошибки при написании кода. Ниже приведен код с правильным отступом, который у меня работает.

Обратите внимание, что я не могу исправлять ошибки в пользовательских кодах, только в «friendly-traceback».


```
class Map:

    def print_map(self):
        for row in self.cells:
            for cell in row:
                if cell == 0:
                    print('🟩', end="")
                elif cell == 1:
                    print('🌲', end="")
                elif cell == 2:
                    print('🌊', end="")
            print()
    def __init__(self, w, h):
         self.cells = [[0 for i in range(w)] for j in range(h)]

tmp = Map(10, 10)
tmp.print_map()
```
![image](https://github.com/friendly-traceback/friendly-traceback/assets/629698/1ea5687e-6d46-4369-88eb-948c2faf508a)
