### ISSUE TITLE
Translate actual error messages from Python

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#49]
This was originally noted in https://github.com/aroberge/friendly/issues/209.

Currently, the answer to `what()` contains two parts:
```
SomeError: message from Python

Explanation of what SomeError means
```
The first part is not considered for translation; the second part is. It might be useful to consider making the original message translatable. This would likely affect how `explain()` works in order to have the translation of the message from Python appear, but ensuring that it does not appear twice when the message cannot be translated (either because English is selected or because a translation has not been created).

**Comment by aroberge** [comment]
Given the content of `why()`, this would most often be some unnecessary duplicate information.

**Comment by qkzk** [comment]
Hello, we're working on a project for young students learning Python.
We can't assume our students speak English...
The whole project is already translated into French and Spanish.
Some parts of the error messages are still in English and this would be a nice addition !

**Comment by aroberge** [comment]
@qkzk I will reopen this issue then. But please note that this is a bit of a lower priority at the moment.

**Comment by qkzk** [comment]
I understand :smile_cat:  thanks !

**Comment by alexmojaki** [comment]
@aroberge some clarifications:

1. The project in question is futurecoder. The French translation was recently completed.
2. @qkzk & co. were interested in writing the translations themselves and contributing to friendly-traceback.
3. After some more discussion, they are reconsidering the idea, since as you say the longer explanation from `why()` usually contains all the information.

**Comment by aroberge** [comment]
Thanks @alexmojaki. I'll still keep the issue open.

**Comment by aroberge** [comment]
Closing this issue as this would significantly increase the work of translators with relatively little benefit.
