### ISSUE TITLE
Typing info

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#62]
Issue created to keep track of typing related issues and commits.

@hoefling I have added a `# type: ignore` comment at the top of some files which do not contain any typing information to reduce the number of errors as I go through and attempt to fix some minor typing issues.  So far, in doing so, I have found one bug where I was returning a string instead of a dict for an hypothetical case.

**Comment by hoefling** [comment]
@aroberge great! I am still working on proper type hints for `runtime_errors` and `syntax_errors`, hopefully we can gradually introduce them in the near future. BTW you can also exclude modules from type checking via globs in `mypy` config in `pyproject.toml`:
```toml
[tool.mypy]
files = ["friendly_traceback"]
...
overrides = [
    { module = "friendly_traceback.runtime_errors.*", ignore_errors = true },
    { module = "friendly_traceback.syntax_errors.*", ignore_errors = true },
]
```
so you don't have to ignore each file separately. But! the approach with placing a `# type: ignore` on top of a file has the benefits that is is understood by any type checker and doesn't need to be configured for each tool again.

**Comment by aroberge** [comment]
@hoefling Thanks for the info about globally ignoring errors. For now, I'll just stick with a comment at the top of the file, so that it should be relatively easy to adding back files one at a time.

I'm thinking of renaming `friendly_traceback.typing` to `friendly_traceback.typing_info` to make the distinction more visible between the typing module in the standard library and the one for this project.  If I do so, I'll add a comment on this issue.

**Comment by aroberge** [comment]
As mentioned in a previous comment, I changed the name of the local file "typing.py" to "typing_info.py".

Closing this issue: I will be working on type annotation at a later time, with no need to relate to a specific issue.
