### ISSUE TITLE
Proposal: use error classes for message registration instead of class names

### ISSUE THREAD

**Issue by hoefling** [friendly-traceback/friendly-traceback#8]
Hi @aroberge,

I am curious about the decision to use error class names as registration keys instead of classes themselves. Do I overlook something? The drawback I see with the string keys is that name clashes (e.g. registering `foo.Error` and `bar.Error`) should be resolved in the `get_cause(value: ErrType, ...)` itself.

**Comment by aroberge** [comment]
@hoefling I used the exception name simply as a habit of using string for dict keys; I didn't spend much time thinking about it. My original goal was (and likely still will be for the foreseeable future) to limit friendly-traceback to standard Python exceptions. 

My guess is that you are thinking of perhaps extending this to add your own exceptions ... If so, I would be open to changing the way I register exceptions.

**Comment by hoefling** [comment]
@aroberge

> My guess is that you are thinking of perhaps extending this to add your own exceptions ...

we indeed do register custom messages for custom error types, and it works great and stable even if the API is not public yet. Using string keys is also fine for now since we're in control of class naming. I rather think about future resolving of possible name clashes coming from different third-party packages, e.g. both `django` and `django-rest-framework` define a `ValidationError`, and adding a custom explanation for those would require matching error type in `get_cause` hook.

**Comment by aroberge** [comment]
Ok, I will make the change. I might be able to get this done this morning.

**Comment by hoefling** [comment]
@aroberge thank you! No rush though - I guess ATM you already have enough to do with the library splitting :-)

**Comment by aroberge** [comment]
@hoefling Actually, as far as I know, the split is completed and I'm just trying to polish things up (including updating the documentation ... which I do not enjoy ...) before doing the 0.4 release.

**Comment by aroberge** [comment]
@hoefling Done!  Version 0.3.159 uploaded to PyPI.

**If you have the time**, I was wondering if you could write a very short explanation that I could include in the documentation  explaining the required steps needed to add explanations for custom exceptions to friendly-traceback.  If you do so, you can simply include the text as an issue in https://github.com/friendly-traceback/docs.  You don't have to use the .rst syntax for this.  

If you don't have the time, it's ok ... I'll get around to it eventually on my own.

**Comment by hoefling** [comment]
@aroberge I will gladly enhance the documentation!
