### ISSUE TITLE
Friendly not using readline

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly-traceback#80]
On Debian typing, inside friendly, `print←←←←←` gives:

```
$ python -m friendly

friendly-traceback: 0.4.60
friendly: 0.4.26
Python: 3.9.8
Type 'Friendly' for help on special functions/methods.

[1]: print^[[D^[[D^[[D^[[D^[[D
```

I mean, if I hit my arrow keys, left, up, right, down, it prints `^[[A`/`^[[B`/`^[[C`/`^[[D` instead of moving through history (for up/down) or inside the line (for left/right).

One can use `rlwrap python -m friendly` as a temporary fix.

**Comment by aroberge** [comment]
Thanks. I will have to figure out how to test this as it works perfectly on Windows, which is what I use. I wonder if the Linux subsystem (which I have never tried) might be helpful in figuring out how to fix this.

**Comment by aroberge** [comment]
Closing as it was moved to https://github.com/friendly-traceback/friendly/issues/17

**Comment by aroberge** [comment]
@JulienPalard Did you install Python by building it?  Reading this StackOverflow question (https://stackoverflow.com/questions/55768178/no-line-history-autocomplete-available-in-python-repl) lead me to this set of instructions https://dzone.com/articles/install-python-370-on-ubuntu-1804debian-95 which mentions the need to use libreadline-dev in the build process.   Is this what you have done?

**Comment by JulienPalard** [comment]
Yes I do compile a lot of Pythons versions myself but I have libreadline-dev when I do so.

And for this particular case I was running the system Python, and in all my Pythons readline do work in the builtin Python REPL.

**Comment by aroberge** [comment]
I've read in a comment today on a video about rlwrap (https://www.youtube.com/watch?v=WizvitXOsLk) that simply adding `import readline` in a program might fix this problem.
Could you do this either in `friendly/__init__` or perhaps in `friendly/console.py` which is where I use `input()`.

On Windows, readline is not present. If this works, then I'll add
```python
try:
   import readline
except ModuleNotFoundError:
   pass
```

**Comment by aroberge** [comment]
@JulienPalard I've attempted to fix this with friendly-traceback version 0.4.70.  Could you see if it works?

**Comment by JulienPalard** [comment]
The behavior is very strange, it "jumps" over the prompt, either using backspace or the left key, see this gif where I try first using backspace, then using the left arrow.

![Peek 14-11-2021 17-18](https://user-images.githubusercontent.com/239510/141689182-f88646e1-ed38-47f5-831a-43f42dca344b.gif)

**Comment by aroberge** [comment]
Thanks for trying it out.  On the plus side, the escape characters are no longer present .... but, I admit that the behaviour is less than ideal.  :(

**Comment by aroberge** [comment]
The same behaviour was reported in https://github.com/willmcgugan/rich/issues/299 ... and fixed there. I do not use Rich's `input()` but Python's.  I will see if I can use Rich's `input()` on Windows and, if so, will upload a new version.

**Comment by JulienPalard** [comment]
It reminds me of a bash bug: the program does not know a prompt was printed, so it thinks it's at the 1st column. When the user hits backspace it thinks it's safe to emit a `\r` to directly jump to the front of the line, but it's not. I'm digging.

**Comment by aroberge** [comment]
Try the new friendly version (0.4.27)

**Comment by JulienPalard** [comment]
Same with 0.4.27. It's easy to reproduce:

```python
import readline

print("[1] ", end="")
input()
```

(Do you need an access to a Linux box to test it? I may be able to provide you with one, if sdf.org is not enough to test this, just ask me.)

**Comment by JulienPalard** [comment]
For my previous reproducer there's an easy fix:

```python
import readline

input("[1] ")
```

**Comment by aroberge** [comment]
Ok, that's what I did with the version.

If it works, I will see if I can do something with the styling as I do not like the default with just using `input`.
