### ISSUE TITLE
Exclude file from traceback no longer working with relative path

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly-traceback#81]
I had the habit of giving \_\_file__ to `exclude_file_from_traceback()`, and I think it worked back then.

But now it does no longer works. I don't really know what changed, so I'm starting to inspect:

Locally on my machine it works, but \_\_file__ is absolute, on HackInScience \_\_file__ contains `./check.py` and it does not work.

If I call exclude_file_from_traceback with `"./check.py"` or `"check.py"` it does not get excluded. 

I don't know if it's indended to work as is, or if `exclude_file_from_traceback` should call `.resolve()` on it before check if the file exists?

**Comment by aroberge** [comment]
I'm not familiar with `.resolve()` but what I am guessing from the name is that this is something that should be done.  I will investigate...

**Comment by JulienPalard** [comment]
I'm investingating in my DB, looks like it changed recently:
```psql
hkis=> select date_trunc('month', created_at) d, 100 * sum(case when correction_message like '%check.py%' then 1 end) / count(1) from website_answer group by d order by d;
 2021-01-01 00:00:00+01 |        0
 2021-02-01 00:00:00+01 |        1
 2021-03-01 00:00:00+01 |        1
 2021-04-01 00:00:00+02 |        2
 2021-05-01 00:00:00+02 |        2
 2021-06-01 00:00:00+02 |        1
 2021-07-01 00:00:00+02 |        2
 2021-08-01 00:00:00+02 |        2
 2021-09-01 00:00:00+02 |        1
 2021-10-01 00:00:00+02 |        1
 2021-11-01 00:00:00+01 |       11
```

We went from 1%±1% during the previous month to 11% this month.

The 1%±1% can be explained easily by me forgetting the exclude line in a few exercises...

**Comment by aroberge** [comment]
I cannot figure out what would have changed recently; perhaps you changed the version of friendly-traceback you used recently.  I propose to replace (copy-pasted)
```python
    if not os.path.isfile(full_path):
        raise RuntimeError(
            f"{full_path} is not a valid file path; it cannot be excluded."
        )
    # full_path could be a pathlib.Path instance
    full_path = str(full_path)
    EXCLUDED_FILE_PATH.add(full_path)
```
by the following (untested)
```python
# full_path could be a pathlib.Path instance
full_path = str(full_path)
full_path = os.path.abspath(full_path)  # new
if not os.path.isfile(full_path):
    raise RuntimeError(
        f"{full_path} is not a valid file path; it cannot be excluded."
    )
    EXCLUDED_FILE_PATH.add(full_path)
```
and do a similar conversion using `os.path.abspath` in `is_excluded_file`.

**Comment by JulienPalard** [comment]
So, I sshd to correction servers to try various versions of friendly-traceback, and now the bug dissapeared.

I had 0.4.62 on both servers, I tried 0.4.59, 0.4.60, 0.4.61, and back to 0.4.62 and no bug.

I hate when this happen.

I'm staring blankly to:

```
    Uninstalling friendly-traceback-0.4.62:
      Successfully uninstalled friendly-traceback-0.4.62
Successfully installed friendly-traceback-0.4.59
```
prooving I was previously using 0.4.62, and all other line showing no other dependencies being updated during the upgrade session... wow...

**Comment by aroberge** [comment]
Weird. Still, I decided to add the conversion to the absolute path *just in case*.  This is in the newest version (0.4.63) just uploaded.

**Comment by JulienPalard** [comment]
So, I tried various versions of friendly-traceback and its dependencies:

```
   28  pip install friendly-traceback==0.4.59
   29  pip install friendly-traceback==0.4.60
   30  pip install friendly-traceback==0.4.61
   31  pip install friendly-traceback==0.4.59
   32  pip install friendly-traceback==0.4.61
   33  pip install friendly-traceback==0.4.62
   34  pip install friendly-traceback==0.4.59
   35  pip install friendly-traceback==0.4.55
   36  pip install friendly-traceback==0.4.59
   37  pip install stack-data==0.1.2
   38  pip install stack-data==0.1.0
   39  pip install pure-eval==0.2.1
   41  pip install asttokens==2.0.4
   42  pip install executing==0.5.3
   43  pip install pure-eval==0.1.1
   44  pip list
   45  pip install friendly-traceback==0.4.55
   46  pip install friendly==0.4.21
   47  pip install friendly-traceback==0.4.39
   48  pip install friendly-traceback==0.4.20
   49  pip install friendly-traceback==0.4.39
```

without being able to make it work with an old version.

**Comment by JulienPalard** [comment]
> Weird. Still, I decided to add the conversion to the absolute path _just in case_. This is in the newest version (0.4.63) just uploaded.

It correctly fixed the issue, thanks \o/ \o/
