### ISSUE TITLE
Proposal: add public type hints

### ISSUE THREAD

**Issue by hoefling** [friendly-traceback/friendly-traceback#9]
Hi @aroberge,
since `friendly` only supports Python 3.6 and onwards, what do you think about (gradually) introducing type hints? We can gladly help, since we already maintain PEP 561 stubs for selected modules.

**Comment by aroberge** [comment]
I currently have no plans to use type hints but I would have no objections in accepting contributions to support them provided they did not create complications dealing with circular imports -- I seem to remember reading that this was a problem in some situations.

**Comment by aroberge** [comment]
You mentioned stub files ...  I have no experience with using type hints but, all things being equal, I would prefer type hints to be included in the .py files themselves rather than in separate files.

**Comment by hoefling** [comment]
@aroberge sure, inline typing is the best option - stubs are only helpful in the case if the library can't/won't accept inline typing for specific reasons.
