### ISSUE TITLE
Cannot handle some invalid int() conversion

### ISSUE THREAD

**Issue by kseistrup** [friendly-traceback/friendly-traceback#90]
```pytb
[1]: int('12')   # no problem
12

[2]: int('1 2')  # let's try with a space between the two digits

Traceback (most recent call last):
  Code block [2], line 1, in <module>
    ValueError: invalid literal for int() with base 10: '1 2'

        Internal error for Friendly.
[…]
```

**Comment by aroberge** [comment]
Thank you for this report.  I will look at it right away.

**Comment by aroberge** [comment]
friendly-traceback has been updated to 0.4.89. 

```
python -m pip install friendly-traceback --upgrade
```

Note that if you installed friendly instead of friendly-traceback as is recommended, friendly-traceback was automatically installed as a dependency, and is where the bug occurred.

**Comment by kseistrup** [comment]
Whauw, that was fast! Thank you so much. I have upgraded `friendly-traceback`.

**Comment by kseistrup** [comment]
Just for the record: I found the bug because Python is somewhat forgiving about strings passed to the `int()` method:

```py
>>> int('  12\t\n')  # wrap the digits in a few blanks
12
```

So I was curious to see what Python would do if digits were separated by one or more blanks.

**Comment by aroberge** [comment]
On Thu, Dec 2, 2021 at 8:51 AM Klaus Alexander Seistrup <
***@***.***> wrote:

> Just for the record: I found the bug because Python is somewhat forgiving
> about strings passed to the int() method:
>
> >>> int('  12\t\n')  # wrap the digits in a few blanks12
>
> So I was curious to see what Python would do if digits were separated by
> one or more blanks.
>
>
> I know, which is why I first start by stripping any surrounding space
before trying to detect invalid characters

https://github.com/friendly-traceback/friendly-traceback/blob/53401c35b9f8a19bd3a1ec2e526bf83ca458eb17/friendly_traceback/runtime_errors/value_error.py#L143

By the way, handling of ValueError for int() was just added a couple of
weeks ago!
