### ISSUE TITLE
Broken filename when cwd is root

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#97]
This code:

```python
import os

import friendly_traceback

os.chdir("/")

try:
    1/0
except:
    friendly_traceback.explain_traceback()
```

cuts off the filename leading to output like `File "ome/alex/...` instead of `/home/alex/...`. The problem is probably these lines in `shorten_path`:

```python
        elif path.startswith(os.getcwd()):
            path = path[len(os.getcwd()) + 1 :]  # exclude separator
```

This was encountered in https://github.com/dodona-edu/papyros/pull/80

**Comment by aroberge** [comment]
I cannot test this as I only work on Windows.  I am guessing that the following would fix the problem:

```
        elif path.startswith(os.getcwd()):
            path = path[len(os.getcwd()):]
            if path.startswith(os.path.sep):
                path = path[1:]
```
Could you possibly confirm?

I am thinking of then adding
```
path = "CWD:" + path
```

**Comment by aroberge** [comment]
If `os.getcwd() == /`, I should simply leave the path unchanged.

**Comment by aroberge** [comment]
Actually, I removed this case altogether.

New version uploaded to pypi (0.4.93)

**Comment by alexmojaki** [comment]
Thanks!
