### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#98]
See https://github.com/friendly-traceback/friendly-traceback/issues/45#issuecomment-962197860 and https://github.com/dodona-edu/papyros/pull/80#issuecomment-997451558

@pdawyndt @winniederidder 

> The following is a draft explanation for the currently unhandled example mentioned in [#80 (comment)](https://github.com/dodona-edu/papyros/pull/80#issuecomment-996880621)
> 
> ```
> Traceback (most recent call last):
>   File "HOME:\github\friendly-traceback\ignore.py", line 2, in <module>
>     for number in numbers:
> RuntimeError: Set changed size during iteration
> 
>     A `RuntimeError` is raised when an error is detected that doesn't fall in any
>     of the more specific exception types defined by Python.
> 
>     While you were iterating over the elements of `numbers` (a `set`)
>     in a `for` or `while` loop, you either tried to add or remove items from it.
>     Suggestion: start by making a copy of `numbers` and iterate over the elements
>     of that copy if you want to change `numbers` inside a loop.
> 
>     Exception raised on line 2 of file HOME:\github\friendly-traceback\ignore.py.
> 
>        1: numbers = {1, 2, 3}
>     -->2: for number in numbers:
>        3:     numbers.add(2 * number)
> 
>             number:  2
>             numbers:  {1, 2, 3, 4}
> ```
> 
> If this meets your approval, it can be added to the next release of friendly-traceback. Feel free to make suggestions for better wording.

This should be an issue here, not part of the papyros discussion.

@aroberge Did you actually implement the detection of the iterable `numbers`? `executing.Source.statements_at_line` should work well for that. Either way, it should be easy to detect the type of loop (for or while), assuming it's actually raised at a loop instead of something like `next()`. But also there's an arrow pointing at it so it's a bit redundant.

You could directly suggest `.copy()` for dicts and sets, in case the user doesn't know how to apply your suggestion.

The other common suggestion is to create a new collection and add the items you want, instead of modifying the original. I understand that may be too much for this message.

Maybe you could link to a resource explaining the overall problem in more detail?

**Comment by aroberge** [comment]
@alexmojaki Yes, I did implement the detection of the iterable numbers using an existing utility function.  Here's the current code:
```python
def container_changed_size_during_iteration(
    message: str, frame: FrameType, tb_data: TracebackData
) -> CauseInfo:
    pattern = re.compile(r"(.*) changed size during iteration")
    match = re.search(pattern, message)
    if not match:
        return {}
    container_name = match.group(1).lower()
    if container_name.startswith("dict"):
        container_name = "dict"
    container_type = info_variables.convert_type(container_name)

    objects = info_variables.get_all_objects(tb_data.bad_line, frame)
    names = []
    for name, obj in objects["name, obj"]:
        if container_name == "dict":
            if isinstance(obj, dict):
                names.append(name)
        elif container_name == "set":
            if isinstance(obj, set):
                names.append(name)

    if len(names) == 1:
        cause = _("While you were iterating over the items of `{name}` ({container_type})\n"
                  "in a `for` or `while` loop, you either tried to add or remove items from it.\n"
                  "Suggestion: start by making a copy of `{name}` and iterate over the items\n"
                  "of that copy if you want to change `{name}` inside a loop.\n"
                  ).format(name=names[0], container_type=container_type)
    else:
        cause = _("While you were iterating over the items of a container ({container_type})\n"
                  "in a `for` or `while` loop, you either tried to add or remove items from it.\n"
                  f"Suggestion: start by making a copy of the container and iterate over the items\n"
                  "of that copy if you want to change that container inside a loop.\n"
                  ).format(name=names[0], container_type=container_type)

    return {"cause": cause}
```
I have been thinking of figuring out what type of loop might be the cause of the problem, and might still do that.

I'm hesitant to add links to sites explaining the error, unless it is the Python docs, as it is not possible to guarantee that the explanation will be available in all supported languages and is not friendly to people that do not understand English.  (The Python docs are translated in various languages.) Following your suggestion about `.copy()`, I might add some sample code; something like:

```
_("You might want to do this as follows:\n"
  "    my_{name} = name.copy()\n"
  "    for item in my_{name}:\n"
  "        # Change {name}\n")
```
